import { sql } from 'drizzle-orm'
import {
  boolean,
  integer,
  pgEnum,
  pgTable,
  primaryKey,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core'
import { user } from './auth-schema'

// Better Auth's tables (user, session, account, verification), generated by
// `npx @better-auth/cli generate`. Don't edit that file by hand.
export * from './auth-schema'

export const stackLayer = pgEnum('stack_layer', [
  'frontendFramework',
  'backendFramework',
  'backendLanguage',
  'database',
])

// `normalizedName` is the lookup key for Alias resolution: see `normalizeName`.
export const skills = pgTable('skills', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  normalizedName: text('normalized_name').notNull().unique(),
  suggestedLayer: stackLayer('suggested_layer'),
})

export const skillAliases = pgTable('skill_aliases', {
  id: serial('id').primaryKey(),
  skillId: integer('skill_id')
    .notNull()
    .references(() => skills.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  normalizedName: text('normalized_name').notNull().unique(),
})

export const targetRoles = pgTable('target_roles', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  normalizedName: text('normalized_name').notNull().unique(),
})

export const targetRoleAliases = pgTable('target_role_aliases', {
  id: serial('id').primaryKey(),
  targetRoleId: integer('target_role_id')
    .notNull()
    .references(() => targetRoles.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  normalizedName: text('normalized_name').notNull().unique(),
})

export const jobSearchStatus = pgEnum('job_search_status', [
  'activelyLooking',
  'employedAndLooking',
  'employedOpenToOffers',
  'notLooking',
])

export const seniority = pgEnum('seniority', [
  'junior',
  'mid',
  'senior',
  'staffPlus',
])

// A Member is created on first GitHub sign-in. `authUserId` points at Better
// Auth's own user row, which holds the sign-in identity. The Discord columns
// stay null until the Member connects Discord. `hidden` marks a Hidden
// Member, whom only the Admin hides and reactivates: kept, but out of the
// Directory. The connected Discord account is checked against TOLC until it
// passes once (ADR 0003): `membershipPassedAt` is when it passed, and
// `membershipCheckedAt` when Discord last answered "not in TOLC" (null if it
// never has, or since refused to answer). `membershipAttemptedAt` is when
// Discord was last asked, answer or not. The profile columns stay null until
// the Member fills the signup form.
export const members = pgTable('members', {
  id: serial('id').primaryKey(),
  authUserId: text('auth_user_id')
    .notNull()
    .unique()
    .references(() => user.id, { onDelete: 'cascade' }),
  discordUserId: text('discord_user_id').unique(),
  discordHandle: text('discord_handle'),
  discordSyncedAt: timestamp('discord_synced_at'),
  hidden: boolean('hidden').default(false).notNull(),
  membershipPassedAt: timestamp('membership_passed_at'),
  membershipCheckedAt: timestamp('membership_checked_at'),
  membershipAttemptedAt: timestamp('membership_attempted_at'),
  firstName: text('first_name'),
  lastName: text('last_name'),
  jobSearchStatus: jobSearchStatus('job_search_status'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
})

export const linkKind = pgEnum('link_kind', [
  'linkedin',
  'github',
  'resume',
  'portfolio',
  'bluesky',
  'custom',
])

// One Link of each kind per Member, except Custom Links, which can repeat.
export const links = pgTable(
  'links',
  {
    id: serial('id').primaryKey(),
    memberId: integer('member_id')
      .notNull()
      .references(() => members.id, { onDelete: 'cascade' }),
    kind: linkKind('kind').notNull(),
    url: text('url').notNull(),
    label: text('label'),
  },
  (table) => [
    uniqueIndex('links_member_kind_unique')
      .on(table.memberId, table.kind)
      .where(sql`${table.kind} <> 'custom'`),
  ],
)

export const memberTargetRoles = pgTable(
  'member_target_roles',
  {
    memberId: integer('member_id')
      .notNull()
      .references(() => members.id, { onDelete: 'cascade' }),
    targetRoleId: integer('target_role_id')
      .notNull()
      .references(() => targetRoles.id, { onDelete: 'cascade' }),
  },
  (table) => [primaryKey({ columns: [table.memberId, table.targetRoleId] })],
)

// Every Seniority a Member would accept; exactly one is Preferred.
export const memberSeniorities = pgTable(
  'member_seniorities',
  {
    memberId: integer('member_id')
      .notNull()
      .references(() => members.id, { onDelete: 'cascade' }),
    seniority: seniority('seniority').notNull(),
    preferred: boolean('preferred').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.memberId, table.seniority] }),
    uniqueIndex('member_seniorities_one_preferred')
      .on(table.memberId)
      .where(sql`${table.preferred}`),
  ],
)

// A Member's Tech Stack. A Skill with a `stackLayer` is a Primary Skill in
// that Layer of the Preferred Stack; one without is a Secondary Skill.
export const memberSkills = pgTable(
  'member_skills',
  {
    memberId: integer('member_id')
      .notNull()
      .references(() => members.id, { onDelete: 'cascade' }),
    skillId: integer('skill_id')
      .notNull()
      .references(() => skills.id, { onDelete: 'cascade' }),
    stackLayer: stackLayer('stack_layer'),
  },
  (table) => [
    primaryKey({ columns: [table.memberId, table.skillId] }),
    uniqueIndex('member_skills_one_per_layer')
      .on(table.memberId, table.stackLayer)
      .where(sql`${table.stackLayer} is not null`),
  ],
)
