import { sql } from 'drizzle-orm'
import {
  integer,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core'
import { user } from './auth-schema'

// Better Auth's tables (user, session, account, verification), generated by
// `npx @better-auth/cli generate`. Don't edit that file by hand.
export * from './auth-schema'

export const stackLayer = pgEnum('stack_layer', [
  'frontendFramework',
  'backendFramework',
  'backendLanguage',
  'database',
])

// `normalizedName` is the lookup key for Alias resolution: see `normalizeName`.
export const skills = pgTable('skills', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  normalizedName: text('normalized_name').notNull().unique(),
  suggestedLayer: stackLayer('suggested_layer'),
})

export const skillAliases = pgTable('skill_aliases', {
  id: serial('id').primaryKey(),
  skillId: integer('skill_id')
    .notNull()
    .references(() => skills.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  normalizedName: text('normalized_name').notNull().unique(),
})

export const targetRoles = pgTable('target_roles', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  normalizedName: text('normalized_name').notNull().unique(),
})

export const targetRoleAliases = pgTable('target_role_aliases', {
  id: serial('id').primaryKey(),
  targetRoleId: integer('target_role_id')
    .notNull()
    .references(() => targetRoles.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  normalizedName: text('normalized_name').notNull().unique(),
})

// A Member is created on first GitHub sign-in and belongs to one Better Auth user.
export const members = pgTable('members', {
  id: serial('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .unique()
    .references(() => user.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
})

export const linkKind = pgEnum('link_kind', [
  'linkedin',
  'github',
  'resume',
  'portfolio',
  'bluesky',
  'custom',
])

// One Link of each kind per Member, except Custom Links, which can repeat.
export const links = pgTable(
  'links',
  {
    id: serial('id').primaryKey(),
    memberId: integer('member_id')
      .notNull()
      .references(() => members.id, { onDelete: 'cascade' }),
    kind: linkKind('kind').notNull(),
    url: text('url').notNull(),
    label: text('label'),
  },
  (table) => [
    uniqueIndex('links_member_kind_unique')
      .on(table.memberId, table.kind)
      .where(sql`${table.kind} <> 'custom'`),
  ],
)
