/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteImport } from './routes/_member'
import { Route as ConnectDiscordRouteImport } from './routes/connect-discord'
import { Route as MembersOnlyRouteImport } from './routes/members-only'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MemberIndexRouteImport } from './routes/_member/index'
import { Route as MemberEditProfileRouteImport } from './routes/_member/edit-profile'
import { Route as MemberMembersMemberIdRouteImport } from './routes/_member/members.$memberId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const MemberRoute = MemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectDiscordRoute = ConnectDiscordRouteImport.update({
  id: '/connect-discord',
  path: '/connect-discord',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersOnlyRoute = MembersOnlyRouteImport.update({
  id: '/members-only',
  path: '/members-only',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const MemberEditProfileRoute = MemberEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberMembersMemberIdRoute = MemberMembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => MemberRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MemberIndexRoute
  '/connect-discord': typeof ConnectDiscordRoute
  '/members-only': typeof MembersOnlyRoute
  '/sign-in': typeof SignInRoute
  '/signup': typeof SignupRoute
  '/edit-profile': typeof MemberEditProfileRoute
  '/members/$memberId': typeof MemberMembersMemberIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/connect-discord': typeof ConnectDiscordRoute
  '/members-only': typeof MembersOnlyRoute
  '/sign-in': typeof SignInRoute
  '/signup': typeof SignupRoute
  '/edit-profile': typeof MemberEditProfileRoute
  '/': typeof MemberIndexRoute
  '/members/$memberId': typeof MemberMembersMemberIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_member': typeof MemberRouteWithChildren
  '/connect-discord': typeof ConnectDiscordRoute
  '/members-only': typeof MembersOnlyRoute
  '/sign-in': typeof SignInRoute
  '/signup': typeof SignupRoute
  '/_member/edit-profile': typeof MemberEditProfileRoute
  '/_member/': typeof MemberIndexRoute
  '/_member/members/$memberId': typeof MemberMembersMemberIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect-discord'
    | '/members-only'
    | '/sign-in'
    | '/signup'
    | '/edit-profile'
    | '/members/$memberId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connect-discord'
    | '/members-only'
    | '/sign-in'
    | '/signup'
    | '/edit-profile'
    | '/'
    | '/members/$memberId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_member'
    | '/connect-discord'
    | '/members-only'
    | '/sign-in'
    | '/signup'
    | '/_member/edit-profile'
    | '/_member/'
    | '/_member/members/$memberId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MemberRoute: typeof MemberRouteWithChildren
  ConnectDiscordRoute: typeof ConnectDiscordRoute
  MembersOnlyRoute: typeof MembersOnlyRoute
  SignInRoute: typeof SignInRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_member': {
      id: '/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-discord': {
      id: '/connect-discord'
      path: '/connect-discord'
      fullPath: '/connect-discord'
      preLoaderRoute: typeof ConnectDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members-only': {
      id: '/members-only'
      path: '/members-only'
      fullPath: '/members-only'
      preLoaderRoute: typeof MembersOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/': {
      id: '/_member/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/edit-profile': {
      id: '/_member/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof MemberEditProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/members/$memberId': {
      id: '/_member/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MemberMembersMemberIdRouteImport
      parentRoute: typeof MemberRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MemberRouteChildren {
  MemberEditProfileRoute: typeof MemberEditProfileRoute
  MemberIndexRoute: typeof MemberIndexRoute
  MemberMembersMemberIdRoute: typeof MemberMembersMemberIdRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberEditProfileRoute: MemberEditProfileRoute,
  MemberIndexRoute: MemberIndexRoute,
  MemberMembersMemberIdRoute: MemberMembersMemberIdRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MemberRoute: MemberRouteWithChildren,
  ConnectDiscordRoute: ConnectDiscordRoute,
  MembersOnlyRoute: MembersOnlyRoute,
  SignInRoute: SignInRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
